//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Web.Script.Serialization;

namespace Classes.StateAndCountry
{
    public partial class Address
    {
    	public Address()
    	{
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    		this.Neighborhood = new HashSet<Classes.MLS.Neighborhood>();
    		this.Office = new HashSet<Classes.MLS.Office>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    		this.WhatsNearByLocation = new HashSet<Classes.WhatsNearBy.WhatsNearByLocation>();
    	}
    
    	public int AddressID { get; set; }
    	public string Address1 { get; set; }
    	public string Address2 { get; set; }
    	public string City { get; set; }
    	public Nullable<int> StateID { get; set; }
    	public string Zip { get; set; }
    	public Nullable<decimal> Latitude { get; set; }
    	public Nullable<decimal> Longitude { get; set; }
    
    	public virtual Classes.StateAndCountry.State State { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.Neighborhood> Neighborhood { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.Office> Office { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.WhatsNearBy.WhatsNearByLocation> WhatsNearByLocation { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class Application
    {
    	public Application()
    	{
    		this.User = new HashSet<Classes.Media352_MembershipProvider.User>();
    	}
    
    	public int ApplicationID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.User> User { get; set; }
    }
}

namespace Classes.MLS
{
    public partial class Builder
    {
    	public Builder()
    	{
    		this.NeighborhoodBuilder = new HashSet<Classes.MLS.NeighborhoodBuilder>();
    		this.BuilderMicrosite = new HashSet<Classes.MLS.BuilderMicrosite>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    	}
    
    	public int BuilderID { get; set; }
    	public string Name { get; set; }
    	public string Image { get; set; }
    	public string Website { get; set; }
    	public string Info { get; set; }
    	public bool Active { get; set; }
    	public string OwnerName { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.NeighborhoodBuilder> NeighborhoodBuilder { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.BuilderMicrosite> BuilderMicrosite { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    }
}

namespace Classes.MLS
{
    public partial class BuilderMicrosite
    {
    	public int BuilderMicrositeID { get; set; }
    	public int BuilderID { get; set; }
    	public int CMMicrositeID { get; set; }
    
    	public virtual Classes.MLS.Builder Builder { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ClickType
    {
    	public ClickType()
    	{
    		this.ShowcaseItemMetric = new HashSet<Classes.Showcase.ShowcaseItemMetric>();
    		this.ShowcaseItemMetricHistorical = new HashSet<Classes.Showcase.ShowcaseItemMetricHistorical>();
    	}
    
    	public int ClickTypeID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemMetric> ShowcaseItemMetric { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemMetricHistorical> ShowcaseItemMetricHistorical { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMMicrosite
    {
    	public CMMicrosite()
    	{
    		this.CMMicrositeUser = new HashSet<Classes.ContentManager.CMMicrositeUser>();
    		this.CMPage = new HashSet<Classes.ContentManager.CMPage>();
    		this.CMSubmittedForm = new HashSet<Classes.ContentManager.CMSubmittedForm>();
    		this.SMItem = new HashSet<Classes.ContentManager.SMItem>();
    		this.Neighborhood = new HashSet<Classes.MLS.Neighborhood>();
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    		this.BuilderMicrosite = new HashSet<Classes.MLS.BuilderMicrosite>();
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    		this.Newsletter = new HashSet<Classes.Newsletters.Newsletter>();
    		this.Office = new HashSet<Classes.MLS.Office>();
    		this.SMItemUser = new HashSet<Classes.ContentManager.SMItemUser>();
    		this.Team = new HashSet<Classes.Media352_MembershipProvider.Team>();
    		this.Showcase = new HashSet<Classes.Showcase.Showcases>();
    	}
    
    	public int CMMicroSiteID { get; set; }
    	public string Name { get; set; }
    	public bool Active { get; set; }
    	public bool Published { get; set; }
    	public string Description { get; set; }
    	public string Location { get; set; }
    	public string Image { get; set; }
    	public string Phone { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMMicrositeUser> CMMicrositeUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> CMPage { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMSubmittedForm> CMSubmittedForm { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItem> SMItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.Neighborhood> Neighborhood { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.BuilderMicrosite> BuilderMicrosite { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.Newsletter> Newsletter { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.Office> Office { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItemUser> SMItemUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.Team> Team { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.Showcases> Showcase { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMMicrositeUser
    {
    	public int CMMicrositeUserID { get; set; }
    	public int CMMicrositeID { get; set; }
    	public int UserID { get; set; }
    
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMPage
    {
    	public CMPage()
    	{
    		this.CMPageRegion = new HashSet<Classes.ContentManager.CMPageRegion>();
    		this.RegionsUsingPage = new HashSet<Classes.ContentManager.CMPageRegion>();
    		this.PagesUsingAsReponse = new HashSet<Classes.ContentManager.CMPage>();
    		this.SpawnedCMPages = new HashSet<Classes.ContentManager.CMPage>();
    		this.CMPageRole = new HashSet<Classes.ContentManager.CMPageRole>();
    		this.CMPageTitle = new HashSet<Classes.ContentManager.CMPageTitle>();
    		this.CMSubmittedForm = new HashSet<Classes.ContentManager.CMSubmittedForm>();
    		this.SMItem = new HashSet<Classes.ContentManager.SMItem>();
    	}
    
    	public int CMPageID { get; set; }
    	public Nullable<int> CMTemplateID { get; set; }
    	public string Title { get; set; }
    	public string FileName { get; set; }
    	public System.DateTime Created { get; set; }
    	public bool Deleted { get; set; }
    	public int UserID { get; set; }
    	public string FormRecipient { get; set; }
    	public Nullable<int> ResponsePageID { get; set; }
    	public bool CanDelete { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public bool MicrositeDefault { get; set; }
    	public bool FeaturedPage { get; set; }
    	public bool NeedsApproval { get; set; }
    	public Nullable<int> OriginalCMPageID { get; set; }
    	public string EditorUserIDs { get; set; }
    	public Nullable<bool> EditorDeleted { get; set; }
    	public Nullable<int> DynamicCollectionID { get; set; }
    
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRegion> CMPageRegion { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRegion> RegionsUsingPage { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> PagesUsingAsReponse { get; set; }
    	public virtual Classes.ContentManager.CMPage ResponsePage { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> SpawnedCMPages { get; set; }
    	public virtual Classes.ContentManager.CMPage OriginalCMPage { get; set; }
    	public virtual Classes.ContentManager.CMTemplate CMTemplate { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRole> CMPageRole { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageTitle> CMPageTitle { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMSubmittedForm> CMSubmittedForm { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItem> SMItem { get; set; }
    	public virtual Classes.DynamicHeader.DynamicCollection DynamicCollection { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMPageRegion
    {
    	public int CMPageRegionID { get; set; }
    	public int CMPageID { get; set; }
    	public string Content { get; set; }
    	public bool CurrentVersion { get; set; }
    	public System.DateTime Created { get; set; }
    	public Nullable<int> UserID { get; set; }
    	public string ContentClean { get; set; }
    	public Nullable<int> LanguageID { get; set; }
    	public bool NeedsApproval { get; set; }
    	public Nullable<int> GlobalAreaCMPageID { get; set; }
    	public string EditorUserIDs { get; set; }
    	public bool Draft { get; set; }
    	public int CMRegionID { get; set; }
    
    	public virtual Classes.ContentManager.CMPage CMPage { get; set; }
    	public virtual Classes.ContentManager.CMPage GlobalAreaCMPage { get; set; }
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    	public virtual Classes.ContentManager.CMRegion CMRegion { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMPageRole
    {
    	public int CMPageRoleID { get; set; }
    	public int CMPageID { get; set; }
    	public int RoleID { get; set; }
    	public bool Editor { get; set; }
    
    	public virtual Classes.ContentManager.CMPage CMPage { get; set; }
    	public virtual Classes.Media352_MembershipProvider.Role Role { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMPageTitle
    {
    	public int CMPageTitleID { get; set; }
    	public int CMPageID { get; set; }
    	public string Title { get; set; }
    	public int LanguageID { get; set; }
    
    	public virtual Classes.ContentManager.CMPage CMPage { get; set; }
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMRegion
    {
    	public CMRegion()
    	{
    		this.CMPageRegion = new HashSet<Classes.ContentManager.CMPageRegion>();
    	}
    
    	public int CMRegionID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRegion> CMPageRegion { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMSubmittedForm
    {
    	public int CMSubmittedFormID { get; set; }
    	public string FormHTML { get; set; }
    	public Nullable<int> ResponsePageID { get; set; }
    	public System.DateTime DateSubmitted { get; set; }
    	public string FormRecipient { get; set; }
    	public bool IsProcessed { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public string UploadedFile { get; set; }
    
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.ContentManager.CMPage ResponsePage { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class CMTemplate
    {
    	public CMTemplate()
    	{
    		this.CMPage = new HashSet<Classes.ContentManager.CMPage>();
    	}
    
    	public int CMTemplateID { get; set; }
    	public string Name { get; set; }
    	public bool Addable { get; set; }
    	public bool MicrositeEnabled { get; set; }
    	public string FileName { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> CMPage { get; set; }
    }
}

namespace Classes.Contacts
{
    public partial class Contact
    {
    	public int ContactID { get; set; }
    	public int ContactTypeID { get; set; }
    	public int ContactStatusID { get; set; }
    	public int ContactTimeID { get; set; }
    	public int ContactMethodID { get; set; }
    	public string FirstName { get; set; }
    	public string LastName { get; set; }
    	public string Phone { get; set; }
    	public string Email { get; set; }
    	public string Message { get; set; }
    	public System.DateTime Created { get; set; }
    	public Nullable<int> AddressID { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public Nullable<int> ShowcaseItemID { get; set; }
    	public Nullable<int> AgentID { get; set; }
    	public Nullable<int> TeamID { get; set; }
    
    	public virtual Classes.Contacts.ContactMethod ContactMethod { get; set; }
    	public virtual Classes.Contacts.ContactStatus ContactStatus { get; set; }
    	public virtual Classes.Contacts.ContactTime ContactTime { get; set; }
    	public virtual Classes.Contacts.ContactType ContactType { get; set; }
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User Agent { get; set; }
    	public virtual Classes.Media352_MembershipProvider.Team Team { get; set; }
    }
}

namespace Classes.Contacts
{
    public partial class ContactMethod
    {
    	public ContactMethod()
    	{
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    	}
    
    	public int ContactMethodID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    }
}

namespace Classes.Contacts
{
    public partial class ContactStatus
    {
    	public ContactStatus()
    	{
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    	}
    
    	public int ContactStatusID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    }
}

namespace Classes.Contacts
{
    public partial class ContactTime
    {
    	public ContactTime()
    	{
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    	}
    
    	public int ContactTimeID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    }
}

namespace Classes.Contacts
{
    public partial class ContactType
    {
    	public ContactType()
    	{
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    	}
    
    	public int ContactTypeID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    }
}

namespace Classes.StateAndCountry
{
    public partial class Country
    {
    	public Country()
    	{
    		this.State = new HashSet<Classes.StateAndCountry.State>();
    	}
    
    	public int CountryID { get; set; }
    	public string Name { get; set; }
    	public string Abb { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.StateAndCountry.State> State { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class Designation
    {
    	public Designation()
    	{
    		this.UserDesignation = new HashSet<Classes.Media352_MembershipProvider.UserDesignation>();
    	}
    
    	public int DesignationID { get; set; }
    	public string Name { get; set; }
    	public string Icon { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserDesignation> UserDesignation { get; set; }
    }
}

namespace Classes.DynamicHeader
{
    public partial class DynamicCollection
    {
    	public DynamicCollection()
    	{
    		this.DynamicImageCollection = new HashSet<Classes.DynamicHeader.DynamicImageCollection>();
    		this.CMPage = new HashSet<Classes.ContentManager.CMPage>();
    	}
    
    	public int DynamicCollectionID { get; set; }
    	public string Name { get; set; }
    	public bool Active { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.DynamicHeader.DynamicImageCollection> DynamicImageCollection { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> CMPage { get; set; }
    }
}

namespace Classes.DynamicHeader
{
    public partial class DynamicImage
    {
    	public DynamicImage()
    	{
    		this.DynamicImageCollection = new HashSet<Classes.DynamicHeader.DynamicImageCollection>();
    	}
    
    	public int DynamicImageID { get; set; }
    	public string Name { get; set; }
    	public string Title { get; set; }
    	public string Link { get; set; }
    	public Nullable<int> Duration { get; set; }
    	public string Caption { get; set; }
    	public bool Active { get; set; }
    	public bool IsVideo { get; set; }
    	public System.DateTime LastUpdated { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.DynamicHeader.DynamicImageCollection> DynamicImageCollection { get; set; }
    }
}

namespace Classes.DynamicHeader
{
    public partial class DynamicImageCollection
    {
    	public int DynamicImageCollectionID { get; set; }
    	public int DynamicImageID { get; set; }
    	public int DynamicCollectionID { get; set; }
    	public short DisplayOrder { get; set; }
    
    	public virtual Classes.DynamicHeader.DynamicCollection DynamicCollection { get; set; }
    	public virtual Classes.DynamicHeader.DynamicImage DynamicImage { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class Filter
    {
    	public Filter()
    	{
    		this.ShowcaseAttribute = new HashSet<Classes.Showcase.ShowcaseAttribute>();
    	}
    
    	public int ShowcaseFilterID { get; set; }
    	public string Type { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseAttribute> ShowcaseAttribute { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class JobTitle
    {
    	public JobTitle()
    	{
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    	}
    
    	public int JobTitleID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    }
}

namespace Classes.SiteLanguages
{
    public partial class Language
    {
    	public Language()
    	{
    		this.SEOData = new HashSet<Classes.SEOComponent.SEOData>();
    		this.CMPageRegion = new HashSet<Classes.ContentManager.CMPageRegion>();
    		this.CMPageTitle = new HashSet<Classes.ContentManager.CMPageTitle>();
    		this.SMItem = new HashSet<Classes.ContentManager.SMItem>();
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    		this.UserLanguageSpoken = new HashSet<Classes.Media352_MembershipProvider.UserLanguageSpoken>();
    		this.SMItemUser = new HashSet<Classes.ContentManager.SMItemUser>();
    		this.TeamLanguageSpoken = new HashSet<Classes.Media352_MembershipProvider.TeamLanguageSpoken>();
    	}
    
    	public int LanguageID { get; set; }
    	public string Culture { get; set; }
    	public string CultureName { get; set; }
    	public bool Active { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.SEOComponent.SEOData> SEOData { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRegion> CMPageRegion { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageTitle> CMPageTitle { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItem> SMItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserLanguageSpoken> UserLanguageSpoken { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItemUser> SMItemUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.TeamLanguageSpoken> TeamLanguageSpoken { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class MailingList
    {
    	public MailingList()
    	{
    		this.MailingListSubscriber = new HashSet<Classes.Newsletters.MailingListSubscriber>();
    		this.MailoutMailingList = new HashSet<Classes.Newsletters.MailoutMailingList>();
    	}
    
    	public int MailingListID { get; set; }
    	public string Name { get; set; }
    	public bool Active { get; set; }
    	public bool Deleted { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.MailingListSubscriber> MailingListSubscriber { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.MailoutMailingList> MailoutMailingList { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class MailingListSubscriber
    {
    	public int MailingListSubscriberID { get; set; }
    	public int MailingListID { get; set; }
    	public int SubscriberID { get; set; }
    	public Nullable<int> NewsletterFormatID { get; set; }
    	public bool Active { get; set; }
    	public System.Guid EntityID { get; set; }
    
    	public virtual Classes.Newsletters.MailingList MailingList { get; set; }
    	public virtual Classes.Newsletters.NewsletterFormat NewsletterFormat { get; set; }
    	public virtual Classes.Newsletters.Subscriber Subscriber { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class Mailout
    {
    	public Mailout()
    	{
    		this.MailoutMailingList = new HashSet<Classes.Newsletters.MailoutMailingList>();
    		this.NewsletterAction = new HashSet<Classes.Newsletters.NewsletterAction>();
    	}
    
    	public int MailoutID { get; set; }
    	public Nullable<int> NewsletterID { get; set; }
    	public System.DateTime Timestamp { get; set; }
    	public System.DateTime DisplayDate { get; set; }
    	public string Title { get; set; }
    	public string Issue { get; set; }
    	public string Description { get; set; }
    	public string Body { get; set; }
    	public string BodyText { get; set; }
    	public string Keywords { get; set; }
    	public Nullable<int> DesignID { get; set; }
    
    	public virtual Classes.Newsletters.Newsletter Newsletter { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.MailoutMailingList> MailoutMailingList { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.NewsletterAction> NewsletterAction { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class MailoutMailingList
    {
    	public int MailoutMailingListID { get; set; }
    	public int MailingListID { get; set; }
    	public int MailoutID { get; set; }
    
    	public virtual Classes.Newsletters.MailingList MailingList { get; set; }
    	public virtual Classes.Newsletters.Mailout Mailout { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class Media
    {
    	public int ShowcaseMediaID { get; set; }
    	public string URL { get; set; }
    	public string Caption { get; set; }
    	public string Thumbnail { get; set; }
    	public int ShowcaseMediaCollectionID { get; set; }
    	public short DisplayOrder { get; set; }
    	public bool Active { get; set; }
    
    	public virtual Classes.Showcase.MediaCollection ShowcaseMediaCollection { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class MediaCollection
    {
    	public MediaCollection()
    	{
    		this.ShowcaseMedia = new HashSet<Classes.Showcase.Media>();
    	}
    
    	public int ShowcaseMediaCollectionID { get; set; }
    	public string Title { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public int ShowcaseMediaTypeID { get; set; }
    	public string TextBlock { get; set; }
    	public Nullable<short> DisplayOrder { get; set; }
    	public bool Active { get; set; }
    	public bool IsFine { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.Media> ShowcaseMedia { get; set; }
    	public virtual Classes.Showcase.MediaType ShowcaseMediaType { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class MediaType
    {
    	public MediaType()
    	{
    		this.ShowcaseMediaCollection = new HashSet<Classes.Showcase.MediaCollection>();
    	}
    
    	public int ShowcaseMediaTypeID { get; set; }
    	public string Type { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.MediaCollection> ShowcaseMediaCollection { get; set; }
    }
}

namespace Classes.MLS
{
    public partial class Neighborhood
    {
    	public Neighborhood()
    	{
    		this.NeighborhoodBuilder = new HashSet<Classes.MLS.NeighborhoodBuilder>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    	}
    
    	public int NeighborhoodID { get; set; }
    	public string Name { get; set; }
    	public string Image { get; set; }
    	public string PriceRange { get; set; }
    	public string Overview { get; set; }
    	public string Amenities { get; set; }
    	public bool Active { get; set; }
    	public bool Featured { get; set; }
    	public int CMMicrositeID { get; set; }
    	public int AddressID { get; set; }
    	public string Phone { get; set; }
    	public string Website { get; set; }
    	public string Directions { get; set; }
    	public bool ShowLotsLand { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.MLS.NeighborhoodBuilder> NeighborhoodBuilder { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    }
}

namespace Classes.MLS
{
    public partial class NeighborhoodBuilder
    {
    	public int NeighborhoodBuilderID { get; set; }
    	public int NeighborhoodID { get; set; }
    	public int BuilderID { get; set; }
    
    	public virtual Classes.MLS.Builder Builder { get; set; }
    	public virtual Classes.MLS.Neighborhood Neighborhood { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class Newsletter
    {
    	public Newsletter()
    	{
    		this.Mailout = new HashSet<Classes.Newsletters.Mailout>();
    	}
    
    	public int NewsletterID { get; set; }
    	public System.DateTime CreatedDate { get; set; }
    	public System.DateTime DisplayDate { get; set; }
    	public bool Active { get; set; }
    	public bool Featured { get; set; }
    	public bool Archived { get; set; }
    	public string Title { get; set; }
    	public string Issue { get; set; }
    	public string Description { get; set; }
    	public string Body { get; set; }
    	public string BodyText { get; set; }
    	public string Keywords { get; set; }
    	public Nullable<int> DesignID { get; set; }
    	public bool Deleted { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public bool NewHomes { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.Mailout> Mailout { get; set; }
    	public virtual Classes.Newsletters.NewsletterDesign NewsletterDesign { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class NewsletterAction
    {
    	public long NewsletterActionID { get; set; }
    	public int NewsletterActionTypeID { get; set; }
    	public int MailoutID { get; set; }
    	public System.DateTime Timestamp { get; set; }
    	public string IPAddress { get; set; }
    	public Nullable<int> SubscriberID { get; set; }
    	public string Email { get; set; }
    	public string Details { get; set; }
    
    	public virtual Classes.Newsletters.Mailout Mailout { get; set; }
    	public virtual Classes.Newsletters.NewsletterActionType NewsletterActionType { get; set; }
    	public virtual Classes.Newsletters.Subscriber Subscriber { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class NewsletterActionType
    {
    	public NewsletterActionType()
    	{
    		this.NewsletterAction = new HashSet<Classes.Newsletters.NewsletterAction>();
    	}
    
    	public int NewsletterActionTypeID { get; set; }
    	public string Type { get; set; }
    	public string DisplayName { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.NewsletterAction> NewsletterAction { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class NewsletterDesign
    {
    	public NewsletterDesign()
    	{
    		this.Newsletter = new HashSet<Classes.Newsletters.Newsletter>();
    	}
    
    	public int NewsletterDesignID { get; set; }
    	public string Name { get; set; }
    	public string Path { get; set; }
    	public string Template { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.Newsletter> Newsletter { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class NewsletterFormat
    {
    	public NewsletterFormat()
    	{
    		this.MailingListSubscriber = new HashSet<Classes.Newsletters.MailingListSubscriber>();
    		this.Subscriber = new HashSet<Classes.Newsletters.Subscriber>();
    	}
    
    	public int NewsletterFormatID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.MailingListSubscriber> MailingListSubscriber { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.Subscriber> Subscriber { get; set; }
    }
}

namespace Classes.Media352_NewsPress
{
    public partial class NewsPress
    {
    	public NewsPress()
    	{
    		this.NewsPressNewsPressCategory = new HashSet<Classes.Media352_NewsPress.NewsPressNewsPressCategory>();
    	}
    
    	public int NewsPressID { get; set; }
    	public string Title { get; set; }
    	public string Author { get; set; }
    	public System.DateTime Date { get; set; }
    	public string Summary { get; set; }
    	public string StoryHTML { get; set; }
    	public bool Featured { get; set; }
    	public bool Active { get; set; }
    	public bool Archived { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_NewsPress.NewsPressNewsPressCategory> NewsPressNewsPressCategory { get; set; }
    }
}

namespace Classes.Media352_NewsPress
{
    public partial class NewsPressCategory
    {
    	public NewsPressCategory()
    	{
    		this.NewsPressNewsPressCategory = new HashSet<Classes.Media352_NewsPress.NewsPressNewsPressCategory>();
    		this.ChildNewsPressCategories = new HashSet<Classes.Media352_NewsPress.NewsPressCategory>();
    	}
    
    	public int NewsPressCategoryID { get; set; }
    	public Nullable<int> NewsPressParentCategoryID { get; set; }
    	public string Name { get; set; }
    	public bool Active { get; set; }
    	public short DisplayOrder { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_NewsPress.NewsPressNewsPressCategory> NewsPressNewsPressCategory { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_NewsPress.NewsPressCategory> ChildNewsPressCategories { get; set; }
    	public virtual Classes.Media352_NewsPress.NewsPressCategory NewsPressParentCategory { get; set; }
    }
}

namespace Classes.Media352_NewsPress
{
    public partial class NewsPressNewsPressCategory
    {
    	public int NewsPressNewsPressCategoryID { get; set; }
    	public int NewsPressID { get; set; }
    	public int NewsPressCategoryID { get; set; }
    
    	public virtual Classes.Media352_NewsPress.NewsPress NewsPress { get; set; }
    	public virtual Classes.Media352_NewsPress.NewsPressCategory NewsPressCategory { get; set; }
    }
}

namespace Classes.MLS
{
    public partial class Office
    {
    	public Office()
    	{
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.UserOffice = new HashSet<Classes.Media352_MembershipProvider.UserOffice>();
    		this.SoldHome = new HashSet<Classes.NewHomes.SoldHome>();
    	}
    
    	public int OfficeID { get; set; }
    	public int MlsID { get; set; }
    	public string Name { get; set; }
    	public string Phone { get; set; }
    	public string Fax { get; set; }
    	public bool HasNewHomes { get; set; }
    	public bool HasRentals { get; set; }
    	public bool Active { get; set; }
    	public string Image { get; set; }
    	public int AddressID { get; set; }
    	public int CMMicrositeID { get; set; }
    	public bool IsMeybohm { get; set; }
    
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserOffice> UserOffice { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.NewHomes.SoldHome> SoldHome { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class OpenHouse
    {
    	public int OpenHouseID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public System.DateTime BeginDate { get; set; }
    	public Nullable<System.DateTime> EndDate { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class PropertyChangeLog
    {
    	public int PropertyChangeLogID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public string Attribute { get; set; }
    	public string OldValue { get; set; }
    	public string NewValue { get; set; }
    	public System.DateTime DateStamp { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class PropertyStatisticsEmailLog
    {
    	public int PropertyStatisticsEmailLogID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public string Email { get; set; }
    	public System.DateTime TimeSent { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Redirects
{
    public partial class Redirect
    {
    	public int RedirectID { get; set; }
    	public string OldUrl { get; set; }
    	public string NewUrl { get; set; }
    }
}

namespace Classes.Rets
{
    public partial class RetsStatus
    {
    	public RetsStatus()
    	{
    		this.RetsTaskStatus = new HashSet<Classes.Rets.RetsTaskStatus>();
    	}
    
    	public int RetsStatusID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Rets.RetsTaskStatus> RetsTaskStatus { get; set; }
    }
}

namespace Classes.Rets
{
    public partial class RetsTask
    {
    	public RetsTask()
    	{
    		this.RetsTaskStatus = new HashSet<Classes.Rets.RetsTaskStatus>();
    	}
    
    	public int RetsTaskID { get; set; }
    	public string TaskName { get; set; }
    	public Nullable<int> ParentRetsTaskID { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Rets.RetsTaskStatus> RetsTaskStatus { get; set; }
    }
}

namespace Classes.Rets
{
    public partial class RetsTaskStatus
    {
    	public int RetsTaskStatusID { get; set; }
    	public int RetsTaskID { get; set; }
    	public int RetsStatusID { get; set; }
    	public System.DateTime TaskCompleteTime { get; set; }
    
    	public virtual Classes.Rets.RetsStatus RetsStatus { get; set; }
    	public virtual Classes.Rets.RetsTask RetsTask { get; set; }
    }
}

namespace Classes.Rets
{
    public partial class RetsUpdatePageTracker
    {
    	public int RetsUpdatePageTrackerID { get; set; }
    	public System.DateTime CurrentRunStartTime { get; set; }
    	public bool RunCompleted { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class Role
    {
    	public Role()
    	{
    		this.UserRole = new HashSet<Classes.Media352_MembershipProvider.UserRole>();
    		this.CMPageRole = new HashSet<Classes.ContentManager.CMPageRole>();
    	}
    
    	public int RoleID { get; set; }
    	public string Name { get; set; }
    	public bool SystemRole { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserRole> UserRole { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRole> CMPageRole { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class SavedSearch
    {
    	public int SavedSearchID { get; set; }
    	public int UserID { get; set; }
    	public Nullable<int> ShowcaseItemID { get; set; }
    	public string Name { get; set; }
    	public string Image { get; set; }
    	public bool EnableEmailNotifications { get; set; }
    	public bool SeparateEmail { get; set; }
    	public bool DailyEmail { get; set; }
    	public System.DateTime Created { get; set; }
    	public int ShowcaseID { get; set; }
    	public string FilterString { get; set; }
    	public Nullable<System.DateTime> LastAlertDate { get; set; }
    	public Nullable<int> LastAlertCount { get; set; }
    	public bool NewHomeSearch { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    	public virtual Classes.Showcase.Showcases Showcase { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class SecurityQuestion
    {
    	public int SecurityQuestionID { get; set; }
    	public string Question { get; set; }
    	public bool Active { get; set; }
    }
}

namespace Classes.SEOComponent
{
    public partial class SEOData
    {
    	public SEOData()
    	{
    		this.UnapprovedSEODatas = new HashSet<Classes.SEOComponent.SEOData>();
    	}
    
    	public int SEODataID { get; set; }
    	public string PageURL { get; set; }
    	public string FriendlyFilename { get; set; }
    	public string Title { get; set; }
    	public string Description { get; set; }
    	public string Keywords { get; set; }
    	public System.DateTime DateCreated { get; set; }
    	public System.DateTime DateLastUpdated { get; set; }
    	public Nullable<int> LanguageID { get; set; }
    	public bool Approved { get; set; }
    	public Nullable<int> ApprovedSEODataID { get; set; }
    
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.SEOComponent.SEOData> UnapprovedSEODatas { get; set; }
    	public virtual Classes.SEOComponent.SEOData ApprovedSEOData { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseAttribute
    {
    	public ShowcaseAttribute()
    	{
    		this.ShowcaseAttributeHeader = new HashSet<Classes.Showcase.ShowcaseAttributeHeader>();
    		this.ShowcaseAttributeValue = new HashSet<Classes.Showcase.ShowcaseAttributeValue>();
    	}
    
    	public int ShowcaseAttributeID { get; set; }
    	public string Title { get; set; }
    	public int ShowcaseFilterID { get; set; }
    	public bool Numeric { get; set; }
    	public bool Active { get; set; }
    	public Nullable<short> DisplayOrder { get; set; }
    	public int ShowcaseID { get; set; }
    	public bool ImportItemAttribute { get; set; }
    	public string MLSAttributeName { get; set; }
    	public Nullable<decimal> MinimumValue { get; set; }
    	public Nullable<decimal> MaximumValue { get; set; }
    	public bool SingleItemValue { get; set; }
    
    	public virtual Classes.Showcase.Showcases Showcase { get; set; }
    	public virtual Classes.Showcase.Filter ShowcaseFilter { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseAttributeHeader> ShowcaseAttributeHeader { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseAttributeValue> ShowcaseAttributeValue { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseAttributeHeader
    {
    	public int ShowcaseAttributeHeaderID { get; set; }
    	public int ShowcaseAttributeID { get; set; }
    	public string Text { get; set; }
    	public bool NoPreferenceColumn { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseAttribute ShowcaseAttribute { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseAttributeValue
    {
    	public ShowcaseAttributeValue()
    	{
    		this.ShowcaseItemAttributeValue = new HashSet<Classes.Showcase.ShowcaseItemAttributeValue>();
    	}
    
    	public int ShowcaseAttributeValueID { get; set; }
    	public string Value { get; set; }
    	public short DisplayOrder { get; set; }
    	public int ShowcaseAttributeID { get; set; }
    	public string UpperRangeValue { get; set; }
    	public bool DisplayInFilters { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseAttribute ShowcaseAttribute { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemAttributeValue> ShowcaseItemAttributeValue { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItem
    {
    	public ShowcaseItem()
    	{
    		this.ShowcaseItemAttributeValue = new HashSet<Classes.Showcase.ShowcaseItemAttributeValue>();
    		this.ShowcaseItemMetric = new HashSet<Classes.Showcase.ShowcaseItemMetric>();
    		this.ShowcaseMediaCollection = new HashSet<Classes.Showcase.MediaCollection>();
    		this.SavedSearch = new HashSet<Classes.Showcase.SavedSearch>();
    		this.PropertyChangeLog = new HashSet<Classes.Showcase.PropertyChangeLog>();
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    		this.ShowcaseItemRental = new HashSet<Classes.Showcase.ShowcaseItemRental>();
    		this.OpenHouse = new HashSet<Classes.Showcase.OpenHouse>();
    		this.SoldHome = new HashSet<Classes.NewHomes.SoldHome>();
    		this.ShowcaseItemMetricHistorical = new HashSet<Classes.Showcase.ShowcaseItemMetricHistorical>();
    		this.PropertyStatisticsEmailLog = new HashSet<Classes.Showcase.PropertyStatisticsEmailLog>();
    		this.ShowcaseItemFinePropertyInformation = new HashSet<Classes.Showcase.ShowcaseItemFinePropertyInformation>();
    	}
    
    	public int ShowcaseItemID { get; set; }
    	public string Title { get; set; }
    	public string Image { get; set; }
    	public string Summary { get; set; }
    	public bool Active { get; set; }
    	public bool Featured { get; set; }
    	public int ShowcaseID { get; set; }
    	public int AddressID { get; set; }
    	public Nullable<int> NeighborhoodID { get; set; }
    	public Nullable<int> BuilderID { get; set; }
    	public Nullable<int> OfficeID { get; set; }
    	public Nullable<int> MlsID { get; set; }
    	public Nullable<decimal> ListPrice { get; set; }
    	public Nullable<System.DateTime> DateListed { get; set; }
    	public Nullable<int> HighSchoolID { get; set; }
    	public Nullable<int> MiddleSchoolID { get; set; }
    	public Nullable<int> ElementarySchoolID { get; set; }
    	public Nullable<int> AgentID { get; set; }
    	public bool Rented { get; set; }
    	public Nullable<System.DateTime> AvailabilityDate { get; set; }
    	public Nullable<int> TeamID { get; set; }
    	public bool StatsSentToAgent { get; set; }
    	public bool StatsSentToOwner { get; set; }
    	public string EmailAddresses { get; set; }
    	public string Website { get; set; }
    	public string Directions { get; set; }
    	public Nullable<int> OpenHouseAgentID { get; set; }
    	public Nullable<int> tempOldID { get; set; }
    	public string VirtualTourURL { get; set; }
    	public bool NewHome { get; set; }
    
    	public virtual Classes.Showcase.Showcases Showcase { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemAttributeValue> ShowcaseItemAttributeValue { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemMetric> ShowcaseItemMetric { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.MediaCollection> ShowcaseMediaCollection { get; set; }
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	public virtual Classes.MLS.Builder Builder { get; set; }
    	public virtual Classes.MLS.Neighborhood Neighborhood { get; set; }
    	public virtual Classes.MLS.Office Office { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User Agent { get; set; }
    	public virtual Classes.WhatsNearBy.WhatsNearByLocation HighSchool { get; set; }
    	public virtual Classes.WhatsNearBy.WhatsNearByLocation MiddleSchool { get; set; }
    	public virtual Classes.WhatsNearBy.WhatsNearByLocation ElementarySchool { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.SavedSearch> SavedSearch { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.PropertyChangeLog> PropertyChangeLog { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemRental> ShowcaseItemRental { get; set; }
    	public virtual Classes.Media352_MembershipProvider.Team Team { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.OpenHouse> OpenHouse { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User OpenHouseAgent { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.NewHomes.SoldHome> SoldHome { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemMetricHistorical> ShowcaseItemMetricHistorical { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.PropertyStatisticsEmailLog> PropertyStatisticsEmailLog { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemFinePropertyInformation> ShowcaseItemFinePropertyInformation { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItemAttributeValue
    {
    	public int ShowcaseItemAttributeValueID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public int ShowcaseAttributeValueID { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseAttributeValue ShowcaseAttributeValue { get; set; }
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItemFinePropertyInformation
    {
    	public int ShowcaseItemFinePropertyInformationId { get; set; }
    	public int ShowcaseItemId { get; set; }
    	public bool IsFine { get; set; }
    	public string Description { get; set; }
    	public bool IsFineFeatured { get; set; }
    	public string Features { get; set; }
    	public string Tags { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItemMetric
    {
    	public int ShowcaseItemMetricID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public string SessionID { get; set; }
    	public System.DateTime Date { get; set; }
    	public int ClickTypeID { get; set; }
    	public Nullable<int> UserID { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    	public virtual Classes.Showcase.ClickType ClickType { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItemMetricHistorical
    {
    	public int ShowcaseItemMetricHistoricalID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public int ClickTypeID { get; set; }
    	public System.DateTime Date { get; set; }
    	public int TotalCount { get; set; }
    
    	public virtual Classes.Showcase.ClickType ClickType { get; set; }
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseItemRental
    {
    	public int ShowcaseItemRentalID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public Nullable<System.DateTime> LeaseBeginDate { get; set; }
    	public string OwnerName { get; set; }
    	public string CompanyName { get; set; }
    	public string ContactName { get; set; }
    	public string ContactPhone { get; set; }
    
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class Showcases
    {
    	public Showcases()
    	{
    		this.ShowcaseAttribute = new HashSet<Classes.Showcase.ShowcaseAttribute>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.ShowcaseSettings = new HashSet<Classes.Showcase.ShowcaseSiteSettings>();
    		this.ShowcaseUser = new HashSet<Classes.Showcase.ShowcaseUser>();
    		this.SavedSearch = new HashSet<Classes.Showcase.SavedSearch>();
    	}
    
    	public int ShowcaseID { get; set; }
    	public string Title { get; set; }
    	public bool Active { get; set; }
    	public bool MLSData { get; set; }
    	public int CMMicrositeID { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseAttribute> ShowcaseAttribute { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseSiteSettings> ShowcaseSettings { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseUser> ShowcaseUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.SavedSearch> SavedSearch { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseSiteSettings
    {
    	public int ShowcaseSettingsID { get; set; }
    	public int ShowcaseID { get; set; }
    	public int SiteSettingsID { get; set; }
    	public string Value { get; set; }
    
    	public virtual Classes.Showcase.Showcases Showcase { get; set; }
    	public virtual Classes.ConfigurationSettings.SiteSettings SiteSettings { get; set; }
    }
}

namespace Classes.Showcase
{
    public partial class ShowcaseUser
    {
    	public int ShowcaseUserID { get; set; }
    	public int ShowcaseID { get; set; }
    	public int UserID { get; set; }
    
    	public virtual Classes.Showcase.Showcases Showcase { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.ConfigurationSettings
{
    public partial class SiteComponent
    {
    	public SiteComponent()
    	{
    		this.SiteSettings = new HashSet<Classes.ConfigurationSettings.SiteSettings>();
    	}
    
    	public int SiteComponentID { get; set; }
    	public string ComponentName { get; set; }
    	public string DisplayName { get; set; }
    	public int MenuDisplayOrder { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ConfigurationSettings.SiteSettings> SiteSettings { get; set; }
    }
}

namespace Classes.ConfigurationSettings
{
    public partial class SiteSettings
    {
    	public SiteSettings()
    	{
    		this.ShowcaseSettings = new HashSet<Classes.Showcase.ShowcaseSiteSettings>();
    	}
    
    	public int SiteSettingsID { get; set; }
    	public string Setting { get; set; }
    	public string Description { get; set; }
    	public string EmbeddedDescription { get; set; }
    	public string Value { get; set; }
    	public System.DateTime DateCreated { get; set; }
    	public System.DateTime DateLastModified { get; set; }
    	public int SiteComponentID { get; set; }
    	public int SiteSettingsDataTypeID { get; set; }
    	public bool IsRequired { get; set; }
    	public string Options { get; set; }
    	public bool IsCustom { get; set; }
    	public byte DisplayOrder { get; set; }
    
    	public virtual Classes.ConfigurationSettings.SiteComponent SiteComponent { get; set; }
    	public virtual Classes.ConfigurationSettings.SiteSettingsDataType SiteSettingsDataType { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseSiteSettings> ShowcaseSettings { get; set; }
    }
}

namespace Classes.ConfigurationSettings
{
    public partial class SiteSettingsDataType
    {
    	public SiteSettingsDataType()
    	{
    		this.SiteSettings = new HashSet<Classes.ConfigurationSettings.SiteSettings>();
    	}
    
    	public int SiteSettingsDataTypeID { get; set; }
    	public string Type { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ConfigurationSettings.SiteSettings> SiteSettings { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class SMItem
    {
    	public SMItem()
    	{
    		this.ChildSMItems = new HashSet<Classes.ContentManager.SMItem>();
    	}
    
    	public int SMItemID { get; set; }
    	public Nullable<int> SMItemParentID { get; set; }
    	public int CMPageID { get; set; }
    	public string Name { get; set; }
    	public short Rank { get; set; }
    	public bool ShowInMenu { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public bool MicrositeDefault { get; set; }
    	public Nullable<int> LanguageID { get; set; }
    	public bool NeedsApproval { get; set; }
    	public Nullable<int> OriginalSMItemID { get; set; }
    	public bool EditorDeleted { get; set; }
    	public Nullable<bool> NewHomes { get; set; }
    
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.ContentManager.CMPage CMPage { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItem> ChildSMItems { get; set; }
    	public virtual Classes.ContentManager.SMItem SMItemParent { get; set; }
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    }
}

namespace Classes.ContentManager
{
    public partial class SMItemUser
    {
    	public int SMItemUserID { get; set; }
    	public int UserID { get; set; }
    	public Nullable<int> CMMicrositeID { get; set; }
    	public bool MicrositeDefault { get; set; }
    	public Nullable<int> LanguageID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    }
}

namespace Classes.NewHomes
{
    public partial class SoldHome
    {
    	public int SoldHomeID { get; set; }
    	public int ShowcaseItemID { get; set; }
    	public Nullable<int> ListingAgentID { get; set; }
    	public Nullable<int> SalesAgentID { get; set; }
    	public Nullable<int> SellerOfficeID { get; set; }
    	public System.DateTime CloseDate { get; set; }
    	public decimal SalePrice { get; set; }
    	public Nullable<decimal> SellerPercentage { get; set; }
    	public Nullable<decimal> SellerOfficePercentage { get; set; }
    	public Nullable<decimal> SalesAgentPercentage { get; set; }
    
    	public virtual Classes.MLS.Office SellerOffice { get; set; }
    	public virtual Classes.Showcase.ShowcaseItem ShowcaseItem { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User ListingAgent { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User SalesAgent { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class StaffType
    {
    	public StaffType()
    	{
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    	}
    
    	public int StaffTypeID { get; set; }
    	public string Name { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    }
}

namespace Classes.StateAndCountry
{
    public partial class State
    {
    	public State()
    	{
    		this.Address = new HashSet<Classes.StateAndCountry.Address>();
    	}
    
    	public int StateID { get; set; }
    	public string Name { get; set; }
    	public string Abb { get; set; }
    	public int CountryID { get; set; }
    	public bool ShipTo { get; set; }
    	public decimal ShippingMarkup { get; set; }
    
    	public virtual Classes.StateAndCountry.Country Country { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.StateAndCountry.Address> Address { get; set; }
    }
}

namespace Classes.Newsletters
{
    public partial class Subscriber
    {
    	public Subscriber()
    	{
    		this.MailingListSubscriber = new HashSet<Classes.Newsletters.MailingListSubscriber>();
    		this.NewsletterAction = new HashSet<Classes.Newsletters.NewsletterAction>();
    	}
    
    	public int SubscriberID { get; set; }
    	public Nullable<int> UserID { get; set; }
    	public string Email { get; set; }
    	public int DefaultNewsletterFormatID { get; set; }
    	public bool Deleted { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.MailingListSubscriber> MailingListSubscriber { get; set; }
    	public virtual Classes.Newsletters.NewsletterFormat NewsletterFormat { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Newsletters.NewsletterAction> NewsletterAction { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class Team
    {
    	public Team()
    	{
    		this.UserTeam = new HashSet<Classes.Media352_MembershipProvider.UserTeam>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.TeamLanguageSpoken = new HashSet<Classes.Media352_MembershipProvider.TeamLanguageSpoken>();
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    	}
    
    	public int TeamID { get; set; }
    	public string Name { get; set; }
    	public string MlsID { get; set; }
    	public int CMMicrositeID { get; set; }
    	public string Photo { get; set; }
    	public string Email { get; set; }
    	public bool DisplayInDirectory { get; set; }
    	public string Phone { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserTeam> UserTeam { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.TeamLanguageSpoken> TeamLanguageSpoken { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class TeamLanguageSpoken
    {
    	public int TeamLanguageSpokenID { get; set; }
    	public int TeamID { get; set; }
    	public int LanguageID { get; set; }
    
    	public virtual Classes.SiteLanguages.Language Languages { get; set; }
    	public virtual Classes.Media352_MembershipProvider.Team Team { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class User
    {
    	public User()
    	{
    		this.UserInfo = new HashSet<Classes.Media352_MembershipProvider.UserInfo>();
    		this.UserRole = new HashSet<Classes.Media352_MembershipProvider.UserRole>();
    		this.CMMicrositeUser = new HashSet<Classes.ContentManager.CMMicrositeUser>();
    		this.CMPageRegion = new HashSet<Classes.ContentManager.CMPageRegion>();
    		this.CMPage = new HashSet<Classes.ContentManager.CMPage>();
    		this.ShowcaseUser = new HashSet<Classes.Showcase.ShowcaseUser>();
    		this.SMItemUser = new HashSet<Classes.ContentManager.SMItemUser>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.SavedSearch = new HashSet<Classes.Showcase.SavedSearch>();
    		this.Contact = new HashSet<Classes.Contacts.Contact>();
    		this.UserOffice = new HashSet<Classes.Media352_MembershipProvider.UserOffice>();
    		this.UserLanguageSpoken = new HashSet<Classes.Media352_MembershipProvider.UserLanguageSpoken>();
    		this.UserTeam = new HashSet<Classes.Media352_MembershipProvider.UserTeam>();
    		this.UserTestimonial = new HashSet<Classes.Media352_MembershipProvider.UserTestimonial>();
    		this.ShowcaseItemMetric = new HashSet<Classes.Showcase.ShowcaseItemMetric>();
    		this.OpenHouseShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.SoldHome = new HashSet<Classes.NewHomes.SoldHome>();
    		this.SoldHome1 = new HashSet<Classes.NewHomes.SoldHome>();
    		this.UserDesignation = new HashSet<Classes.Media352_MembershipProvider.UserDesignation>();
    		this.UserOpenAuthProvider = new HashSet<Classes.Media352_MembershipProvider.UserOpenAuthProvider>();
    	}
    
    	public int UserID { get; set; }
    	public int ApplicationID { get; set; }
    	public string Name { get; set; }
    	public string Email { get; set; }
    	public bool IsApproved { get; set; }
    	public int UniqueEmail { get; set; }
    	public string Salt { get; set; }
    	public string Password { get; set; }
    	public string PasswordQuestion { get; set; }
    	public string PasswordAnswer { get; set; }
    	public int PasswordFormat { get; set; }
    	public System.DateTime Created { get; set; }
    	public System.DateTime LastLogin { get; set; }
    	public System.DateTime LastActivity { get; set; }
    	public System.DateTime LastPasswordChange { get; set; }
    	public Nullable<System.DateTime> LastLockout { get; set; }
    	public int FailedPasswordAttempts { get; set; }
    	public int FailedAnswerAttempts { get; set; }
    	public bool Deleted { get; set; }
    	public bool Locked { get; set; }
    	public bool Online { get; set; }
    	public Nullable<System.Guid> ChangePasswordID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.Application Application { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserInfo> UserInfo { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserRole> UserRole { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMMicrositeUser> CMMicrositeUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPageRegion> CMPageRegion { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.CMPage> CMPage { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseUser> ShowcaseUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.ContentManager.SMItemUser> SMItemUser { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.SavedSearch> SavedSearch { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Contacts.Contact> Contact { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserOffice> UserOffice { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserLanguageSpoken> UserLanguageSpoken { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserTeam> UserTeam { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserTestimonial> UserTestimonial { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItemMetric> ShowcaseItemMetric { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> OpenHouseShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.NewHomes.SoldHome> SoldHome { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.NewHomes.SoldHome> SoldHome1 { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserDesignation> UserDesignation { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Media352_MembershipProvider.UserOpenAuthProvider> UserOpenAuthProvider { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserDesignation
    {
    	public int UserDesignationID { get; set; }
    	public int UserID { get; set; }
    	public int DesignationID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.Designation Designation { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserInfo
    {
    	public int UserInfoID { get; set; }
    	public int UserID { get; set; }
    	public string FirstName { get; set; }
    	public string LastName { get; set; }
    	public Nullable<int> AddressID { get; set; }
    	public Nullable<int> PreferredLanguageID { get; set; }
    	public Nullable<int> PreferredCMMicrositeID { get; set; }
    	public Nullable<int> StaffTypeID { get; set; }
    	public string Website { get; set; }
    	public string HomePhone { get; set; }
    	public string CellPhone { get; set; }
    	public string Fax { get; set; }
    	public string Photo { get; set; }
    	public string Biography { get; set; }
    	public Nullable<int> JobTitleID { get; set; }
    	public Nullable<decimal> Rating { get; set; }
    	public bool ShowRatingOnSite { get; set; }
    	public string OfficePhone { get; set; }
    	public bool ShowListingLink { get; set; }
    	public bool DisplayInDirectory { get; set; }
    	public string PrimaryPhone { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	public virtual Classes.ContentManager.CMMicrosite CMMicrosite { get; set; }
    	public virtual Classes.SiteLanguages.Language Languages { get; set; }
    	public virtual Classes.Media352_MembershipProvider.StaffType StaffType { get; set; }
    	public virtual Classes.Media352_MembershipProvider.JobTitle JobTitle { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserLanguageSpoken
    {
    	public int UserLanguageSpokenID { get; set; }
    	public int UserID { get; set; }
    	public int LanguageID { get; set; }
    
    	public virtual Classes.SiteLanguages.Language Language { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserOffice
    {
    	public int UserOfficeID { get; set; }
    	public int UserID { get; set; }
    	public int OfficeID { get; set; }
    	public string MlsID { get; set; }
    
    	public virtual Classes.MLS.Office Office { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserOpenAuthProvider
    {
    	public int UserOpenAuthProviderID { get; set; }
    	public int UserID { get; set; }
    	public string ProviderName { get; set; }
    	public string ProviderID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserRole
    {
    	public int UserRoleID { get; set; }
    	public int UserID { get; set; }
    	public int RoleID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.Role Role { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserTeam
    {
    	public int UserTeamID { get; set; }
    	public int UserID { get; set; }
    	public int TeamID { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.Team Team { get; set; }
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Media352_MembershipProvider
{
    public partial class UserTestimonial
    {
    	public int UserTestimonialID { get; set; }
    	public int UserID { get; set; }
    	public string Testimonial { get; set; }
    	public string GiverNameAndLocation { get; set; }
    
    	public virtual Classes.Media352_MembershipProvider.User User { get; set; }
    }
}

namespace Classes.Videos
{
    public partial class Video
    {
    	public int VideoID { get; set; }
    	public string Title { get; set; }
    	public string Url { get; set; }
    	public bool Active { get; set; }
    	public bool Featured { get; set; }
    	public System.DateTime DateAdded { get; set; }
    	public short DisplayOrder { get; set; }
    }
}

namespace Classes.WhatsNearBy
{
    public partial class WhatsNearByCategory
    {
    	public WhatsNearByCategory()
    	{
    		this.WhatsNearByLocationCategory = new HashSet<Classes.WhatsNearBy.WhatsNearByLocationCategory>();
    	}
    
    	public int WhatsNearByCategoryID { get; set; }
    	public string Name { get; set; }
    	public bool Active { get; set; }
    	public string PlaceholderImage { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.WhatsNearBy.WhatsNearByLocationCategory> WhatsNearByLocationCategory { get; set; }
    }
}

namespace Classes.WhatsNearBy
{
    public partial class WhatsNearByLocation
    {
    	public WhatsNearByLocation()
    	{
    		this.WhatsNearByLocationCategory = new HashSet<Classes.WhatsNearBy.WhatsNearByLocationCategory>();
    		this.ShowcaseItem = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.ShowcaseItem1 = new HashSet<Classes.Showcase.ShowcaseItem>();
    		this.ShowcaseItem2 = new HashSet<Classes.Showcase.ShowcaseItem>();
    	}
    
    	public int WhatsNearByLocationID { get; set; }
    	public string Name { get; set; }
    	public string Phone { get; set; }
    	public string Website { get; set; }
    	public string Description { get; set; }
    	public bool Active { get; set; }
    	public int AddressID { get; set; }
    	public string Image { get; set; }
    
    	[ScriptIgnore]
    	public virtual ICollection<Classes.WhatsNearBy.WhatsNearByLocationCategory> WhatsNearByLocationCategory { get; set; }
    	public virtual Classes.StateAndCountry.Address Address { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem1 { get; set; }
    	[ScriptIgnore]
    	public virtual ICollection<Classes.Showcase.ShowcaseItem> ShowcaseItem2 { get; set; }
    }
}

namespace Classes.WhatsNearBy
{
    public partial class WhatsNearByLocationCategory
    {
    	public int WhatsNearByLocationCategoryID { get; set; }
    	public int WhatsNearByLocationID { get; set; }
    	public int WhatsNearByCategoryID { get; set; }
    
    	public virtual Classes.WhatsNearBy.WhatsNearByCategory WhatsNearByCategory { get; set; }
    	public virtual Classes.WhatsNearBy.WhatsNearByLocation WhatsNearByLocation { get; set; }
    }
}

public partial class CUSTOM_ELMAH_GetRETSErrors_New_Result
{
	public string ErrorMessage { get; set; }
	public string ErrorData { get; set; }
	public System.DateTime ErrorTimeUtc { get; set; }
	public string Method { get; set; }
	public string City { get; set; }
	public string MlsID { get; set; }
	public string Step { get; set; }
	public string Showcase { get; set; }
}
public partial class CUSTOM_ELMAH_GetRETSErrors_Result
{
	public string ErrorMessage { get; set; }
	public string ErrorData { get; set; }
	public System.DateTime ErrorTimeUtc { get; set; }
}
public partial class CUSTOM_Membership_GetCustomerListForCSV_Result
{
	public int UserID { get; set; }
	public string Name { get; set; }
	public string Email { get; set; }
	public System.DateTime Created { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public string HomePhone { get; set; }
	public string Address1 { get; set; }
	public string Address2 { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string Zip { get; set; }
	public string Preferred_Market { get; set; }
	public string Preferred_Language { get; set; }
}
public partial class CUSTOM_WhatsNearBy_GetLocationsNearCoordinates_Result
{
	public int WhatsNearByLocationID { get; set; }
	public int AddressID { get; set; }
	public string Name { get; set; }
	public string Phone { get; set; }
	public string Website { get; set; }
	public string Description { get; set; }
	public string Image { get; set; }
	public bool Active { get; set; }
	public Nullable<decimal> DistanceAway { get; set; }
}
public partial class DynamicSitemap_URLAndTitle
{
	public string URL { get; set; }
	public string Title { get; set; }
}
public partial class MailingListSubscribersWithEmails
{
	public int SubscriberID { get; set; }
	public string Email { get; set; }
	public int DefaultNewsletterFormatID { get; set; }
	public System.Guid EntityID { get; set; }
}
public partial class Membership_CustomerListForCSV
{
	public int UserID { get; set; }
	public string Name { get; set; }
	public string Email { get; set; }
	public System.DateTime Created { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public string HomePhone { get; set; }
	public string Address1 { get; set; }
	public string Address2 { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string Zip { get; set; }
	public string Preferred_Market { get; set; }
	public string Preferred_Language { get; set; }
}
public partial class NearbyLocations
{
	public int WhatsNearByLocationID { get; set; }
	public int AddressID { get; set; }
	public string Name { get; set; }
	public string Phone { get; set; }
	public string Website { get; set; }
	public string Description { get; set; }
	public string Image { get; set; }
	public bool Active { get; set; }
	public Nullable<decimal> DistanceAway { get; set; }
	public string CategoryNames { get; set; }
}
public partial class Showcase_GetFilteredShowcaseAttributeIDs_Result
{
	public int ShowcaseAttributeID { get; set; }
	public string Value { get; set; }
}
public partial class Showcase_GetFilteredShowcaseAttributeMinMax_Result
{
	public int ShowcaseAttributeID { get; set; }
	public string Title { get; set; }
	public Nullable<int> MinValue { get; set; }
	public Nullable<int> MaxValue { get; set; }
}
public partial class ShowcaseItemForJSON
{
	public int ShowcaseItemID { get; set; }
	public string Title { get; set; }
	public string Image { get; set; }
	public string Summary { get; set; }
	public Nullable<decimal> GeocodedLat { get; set; }
	public Nullable<decimal> GeocodedLong { get; set; }
	public string Address { get; set; }
	public string City { get; set; }
	public string State { get; set; }
	public string Zipcode { get; set; }
	public Nullable<long> Row_Number { get; set; }
	public Nullable<int> TotalRowCount { get; set; }
	public string VirtualTourURL { get; set; }
	public Nullable<bool> HasOpenHouse { get; set; }
}
